version: '3'

services:
  upbasededatos:
    container_name: upbasededatos
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: Local-Devsecops
    ports:
      - "5432:5432"
    networks:
      - mynetwork
    volumes:
      - ./scripts/BD/init.sql:/docker-entrypoint-initdb.d/init.sql

  runningapp:
    container_name: runningapp
    build: .
    command:  ["bash", "-c", "sleep 8 && python run.py && tail -f /dev/null"]
    ports:
      - "5000:5000"
    depends_on:
      - upbasededatos
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
