name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Check Project Files
        run: |
          ls -R

      - name: Synk Analysis
        run: |
          synk analyze --json > resultados_analisis_synk_${{ github.run_id }}.json

      - name: Upload Synk Results
        uses: actions/upload-artifact@v2
        with:
          name: resultados-analisis-synk
          path: resultados_analisis_synk_${{ github.run_id }}.json


