name: Analisis-Dependencias

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
      - name: Check Project Files
        run: |
          ls -R
      - name: Install Snyk
        run: |
          npm install -g snyk
          snyk --version  
      - name: Verificar Contenido de la Carpeta de Trabajo
        run: |
          ls -R
      - name: Snyk Analysis
        run: |
          snyk test --json > resultados_analisis_snyk.json
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_API_KEY }}

      - name: Show Snyk Analysis Results
        run: cat resultados_analisis_snyk.json

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            resultados_analisis_snyk.json
          tag_name: v1.0.0  
          label: "Snyk Analysis JSON"
          token: ${{ secrets.TOKEN_GIT }}

      - name: Get Release URL
        id: get_release_url
        run: echo "::set-output name=url::${{ steps.create_release.outputs.upload_url }}"

      - name: Display Release URL
        run: echo "${{ steps.get_release_url.outputs.url }}"

